version: "3.8"
services:
  app:
    image: mcr.microsoft.com/devcontainers/go:1-ubuntu
    volumes:
      - ..:/workspace:cached
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    command: "go run main.go"
  postgres:
    image: postgres:latest
    container_name: sphinx_postgres
    restart: always
    environment:
      POSTGRES_DB: sphinx_tribes
      POSTGRES_USER: sphinx_user
      POSTGRES_PASSWORD: sphinx_password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:


