version: "3.8"
services:
  app:
    build:
      # This context goes from the compose file location to the repo root.
      context: ../..
      # Path to the Dockerfile from the repo root.
      dockerfile: .devcontainer/Dockerfile.app
    volumes:
      - ..:/workspace:cached
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    command: "go run main.go"
  postgres:
    image: postgres:latest
    container_name: sphinx_postgres
    restart: always
    environment:
      POSTGRES_DB: sphinx_tribes
      POSTGRES_USER: sphinx_user
      POSTGRES_PASSWORD: sphinx_password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:


