version: "3.8"
services:
  app:
    build:
      context: ../..
      dockerfile: .devcontainer/Dockerfile.app
    working_dir: /workspaces/sphinx-tribes
    volumes:
      - ..:/workspaces/sphinx-tribes:cached
    ports:
      - "8080:8080"
    depends_on:
      - postgres
  postgres:
    image: postgres:14
    container_name: sphinx_postgres
    restart: always
    environment:
      POSTGRES_DB: sphinx_tribes
      POSTGRES_USER: sphinx_user
      POSTGRES_PASSWORD: sphinx_password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:


